[features]
seeds = false
skip-lint = false
[programs.localnet]
openbook_v2 = "E6cNbXn2BNoMjXUg7biSTYhmTuyJWQtAnRX1fVPa7y5v"

[registry]
url = "https://rpc-devnet.helius.xyz/?api-key=f7737f45-0d3f-48a3-983c-8b2338d15df5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
